# Copyright 2013, Qualcomm Innovation Center, Inc.
#
#    All rights reserved.
#    This file is licensed under the 3-clause BSD license in the NOTICE.txt
#    file for this project. A copy of the 3-clause BSD license is found at:
#
#        http://opensource.org/licenses/BSD-3-Clause. 
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the license is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the license for the specific language governing permissions and
#    limitations under the license.

Import('samples_env')

# Set the ABI based on the CPU
if samples_env['CPU'] == 'arm':
    android_eabi = 'armeabi'
else:
    android_eabi = 'x86'

samples_env.Append(LIBS = ['OpenSLES'])


# Sink sample
sink_srcs = samples_env.Glob('Sink/jni/*.cc')
sink_objs = samples_env.SharedObject(sink_srcs)
libAllJoynAudioSink = samples_env.SharedLibrary('AllJoynAudioSink', sink_objs)

samples_env.Install('$AUDIO_DISTDIR/samples/Sink/libs/%s' % android_eabi, libAllJoynAudioSink)

# Source library
source_srcs = samples_env.Glob('Source/Library/jni/*.cc')
source_objs = samples_env.SharedObject(source_srcs)
libeasy_alljoyn_audio_service = samples_env.SharedLibrary('easy_alljoyn_audio_service', source_objs)
samples_env.Install('$AUDIO_DISTDIR/lib', libeasy_alljoyn_audio_service)

alljoynaudioservicelibrary_classes = samples_env.Java('$CLASSDIR', source = ['Source/Library/src'])
samples_env.Jar('$AUDIO_DISTDIR/jar/alljoynaudioservicelibrary.jar', source = [alljoynaudioservicelibrary_classes])

# Source sample
samples_env.Install('$AUDIO_DISTDIR/samples/Source/Library/bin', '$AUDIO_DISTDIR/jar/alljoynaudioservicelibrary.jar')
samples_env.Install('$AUDIO_DISTDIR/samples/Source/Library/libs/%s' % android_eabi, '$AUDIO_DISTDIR/lib/libeasy_alljoyn_audio_service.so')

#samples_env.Install('$AUDIO_JAVA_DISTDIR/samples', 'README.txt')

