# Copyright 2013, Qualcomm Innovation Center, Inc.
#
#    All rights reserved.
#    This file is licensed under the 3-clause BSD license in the NOTICE.txt
#    file for this project. A copy of the 3-clause BSD license is found at:
#
#        http://opensource.org/licenses/BSD-3-Clause. 
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the license is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the license for the specific language governing permissions and
#    limitations under the license.

Import('audio_env')

# Sources
srcs = [ f for f in audio_env.Glob('*.cc') if not (str(f).endswith('version.cc')) ]
srcs += [ f for f in audio_env.Glob('*.c') ]

# ALAC
if audio_env.has_key('ALAC_BASE'):
    audio_env.Append(CPPDEFINES = ['WITH_ALAC'])
    srcs += audio_env.Glob('alac/*.cc')
    audio_env.Append(CPPFLAGS = ['-Wno-multichar'])
    audio_env.Append(CPPPATH = ['$ALAC_BASE/codec'])
    audio_env.Append(LIBPATH = ['$ALAC_BASE/codec']);
    audio_env.Append(LIBS = ['alac'])


# Platform specific sources
if audio_env['OS'] == 'android':
    srcs += [ f for f in audio_env.Glob('$OS/*.cc') ]
else:
    srcs += [ f for f in audio_env.Glob('$OS_GROUP/*.cc') ]


version_cc = audio_env.GenVersion('version')

libs = []

# Static library
objs = audio_env.Object(srcs)
audio_env.Depends(version_cc, objs)
objs.append(audio_env.Object(version_cc))
libs.append(audio_env.StaticLibrary('alljoyn_audio', objs))

# Shared library
if audio_env.get('LIBTYPE', 'static') != 'static':
    shobjs = audio_env.SharedObject(srcs)
    audio_env.Depends(version_cc, shobjs)
    shobjs.append(audio_env.SharedObject(version_cc))
    libs.append(audio_env.SharedLibrary('alljoyn_audio', shobjs))

Return('libs')
