# Copyright 2013, Qualcomm Innovation Center, Inc.
#
#    All rights reserved.
#    This file is licensed under the 3-clause BSD license in the NOTICE.txt
#    file for this project. A copy of the 3-clause BSD license is found at:
#
#        http://opensource.org/licenses/BSD-3-Clause. 
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the license is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the license for the specific language governing permissions and
#    limitations under the license.

Import('env')

# Platform specific libraries
if env['OS'] == 'android':
    env.Append(LIBS = ['OpenSLES'])
elif env['OS_GROUP'] == 'posix':
    env.Append(LIBS = ['asound'])

# Sample programs
progs = [
    env.Program('SinkClient',  ['SinkClient.cc']),
    env.Program('SinkService',  ['SinkService.cc']),
    ]

# The return value is the collection of files installed in the build destination.
returnValue = []

if env['OS'] != 'android':
    returnValue += env.Install('$AUDIO_CPP_DISTDIR/bin/samples', progs)
    returnValue += env.Install('$AUDIO_CPP_DISTDIR/samples', env.Glob('*.cc'))
    returnValue += env.Install('$AUDIO_CPP_DISTDIR/samples', 'README.txt')

Return ('returnValue')
